## Notebook for intial data exploration

In [50]:
import pandas as pd 
import glob

In [46]:
df = pd.read_csv(r"..\data\raw\df_fuel_ckan.csv")

In [11]:
df.head()

,DATETIME,GAS,COAL,NUCLEAR,WIND,WIND_EMB,HYDRO,IMPORTS,BIOMASS,OTHER,...,IMPORTS_perc,BIOMASS_perc,OTHER_perc,SOLAR_perc,STORAGE_perc,GENERATION_perc,LOW_CARBON_perc,ZERO_CARBON_perc,RENEWABLE_perc,FOSSIL_perc
0,2009-01-01T00:00:00,8367.0,15037.0,7099.0,248.0,62.0,246.0,2518.0,0.0,0.0,...,7.5,0.0,0.0,0.0,0.0,100.0,22.8,24.5,1.7,69.7
1,2009-01-01T00:30:00,8495.0,15095.0,7088.0,229.0,57.0,245.0,2495.0,0.0,0.0,...,7.4,0.0,0.0,0.0,0.0,100.0,22.6,24.3,1.6,70.0
2,2009-01-01T01:00:00,8471.0,15088.0,7074.0,207.0,52.0,246.0,2465.0,0.0,0.0,...,7.3,0.0,0.0,0.0,0.0,100.0,22.6,24.2,1.5,70.1
3,2009-01-01T01:30:00,8318.0,15035.0,7064.0,191.0,48.0,246.0,2439.0,0.0,0.0,...,7.3,0.0,0.0,0.0,0.0,100.0,22.6,24.3,1.5,70.0
4,2009-01-01T02:00:00,8295.0,15005.0,7052.0,175.0,44.0,246.0,2363.0,0.0,0.0,...,7.1,0.0,0.0,0.0,0.0,100.0,22.7,24.3,1.4,70.2

In [15]:
df.tail()

,DATETIME,GAS,COAL,NUCLEAR,WIND,WIND_EMB,HYDRO,IMPORTS,BIOMASS,OTHER,...,IMPORTS_perc,BIOMASS_perc,OTHER_perc,SOLAR_perc,STORAGE_perc,GENERATION_perc,LOW_CARBON_perc,ZERO_CARBON_perc,RENEWABLE_perc,FOSSIL_perc
306214,2026-06-20T11:00:00,5016.0,0.0,2946.0,4062.0,880.0,195.0,8378.0,1121.0,650.0,...,25.3,3.4,2.0,29.8,0.0,100.0,57.6,59.5,45.3,15.1
306215,2026-06-20T11:30:00,4788.0,0.0,2946.0,4285.0,894.0,181.0,8380.0,1177.0,553.0,...,25.1,3.5,1.7,30.6,0.0,100.0,59.0,61.7,46.7,14.3
306216,2026-06-20T12:00:00,4659.0,0.0,2948.0,4291.0,868.0,179.0,8356.0,1251.0,570.0,...,24.9,3.7,1.7,31.1,0.0,100.0,59.5,62.4,47.0,13.9
306217,2026-06-20T12:30:00,5004.0,0.0,2943.0,4124.0,876.0,180.0,8356.0,1286.0,512.0,...,25.0,3.8,1.5,30.4,0.0,100.0,58.5,60.7,45.9,15.0
306218,2026-06-20T13:00:00,4982.0,0.0,2943.0,4119.0,882.0,180.0,8332.0,1306.0,511.0,...,25.0,3.9,1.5,30.3,0.0,100.0,58.6,60.9,45.8,14.9

In [8]:
df.shape

(306219, 34)

In [21]:
df.columns

Index(['DATETIME', 'GAS', 'COAL', 'NUCLEAR', 'WIND', 'WIND_EMB', 'HYDRO',
       'IMPORTS', 'BIOMASS', 'OTHER', 'SOLAR', 'STORAGE', 'GENERATION',
       'CARBON_INTENSITY', 'LOW_CARBON', 'ZERO_CARBON', 'RENEWABLE', 'FOSSIL',
       'GAS_perc', 'COAL_perc', 'NUCLEAR_perc', 'WIND_perc', 'WIND_EMB_perc',
       'HYDRO_perc', 'IMPORTS_perc', 'BIOMASS_perc', 'OTHER_perc',
       'SOLAR_perc', 'STORAGE_perc', 'GENERATION_perc', 'LOW_CARBON_perc',
       'ZERO_CARBON_perc', 'RENEWABLE_perc', 'FOSSIL_perc'],
      dtype='object')

In [19]:
df.isnull().sum()

DATETIME            0
GAS                 0
COAL                0
NUCLEAR             0
WIND                0
WIND_EMB            0
HYDRO               0
IMPORTS             0
BIOMASS             0
OTHER               0
SOLAR               0
STORAGE             0
GENERATION          0
CARBON_INTENSITY    0
LOW_CARBON          0
ZERO_CARBON         0
RENEWABLE           0
FOSSIL              0
GAS_perc            0
COAL_perc           0
NUCLEAR_perc        0
WIND_perc           0
WIND_EMB_perc       0
HYDRO_perc          0
IMPORTS_perc        0
BIOMASS_perc        0
OTHER_perc          0
SOLAR_perc          0
STORAGE_perc        0
GENERATION_perc     0
LOW_CARBON_perc     0
ZERO_CARBON_perc    0
RENEWABLE_perc      0
FOSSIL_perc         0
dtype: int64

In [47]:
df = df.drop(columns=['GENERATION','CARBON_INTENSITY', 
       'LOW_CARBON', 'ZERO_CARBON', 'RENEWABLE', 'FOSSIL',
       'GAS_perc', 'COAL_perc', 'NUCLEAR_perc', 'WIND_perc', 'WIND_EMB_perc',
       'HYDRO_perc', 'IMPORTS_perc', 'BIOMASS_perc', 'OTHER_perc',
       'SOLAR_perc', 'STORAGE_perc', 'GENERATION_perc', 'LOW_CARBON_perc',
       'ZERO_CARBON_perc', 'RENEWABLE_perc', 'FOSSIL_perc'], axis=1)
# Drop derived data

In [34]:
time_df = pd.DataFrame(columns=['datetime', 'date', 'month', 'year', 'season'])
time_df.head()

Empty DataFrame
Columns: [datetime, date, month, year, season]
Index: []

In [ ]:
time_df = pd.DataFrame({'datetime': df['DATETIME'].drop_duplicates()})
time_df.head()

              datetime
0  2009-01-01T00:00:00
1  2009-01-01T00:30:00
2  2009-01-01T01:00:00
3  2009-01-01T01:30:00
4  2009-01-01T02:00:00

In [39]:
parsed = pd.to_datetime(time_df['datetime'])

time_df['date'] = parsed.dt.strftime('%Y-%m-%d')
time_df['month'] = parsed.dt.month
time_df['year'] = parsed.dt.year

month_to_season = {12:'winter', 1:'winter', 2:'winter', 3:'spring', 4:'spring', 5:'spring', 6:'summer', 7:'summer', 8:'summer', 9:'autumn', 10:'autumn', 11:'autumn'}

time_df['season'] = time_df['month'].map(month_to_season)

In [42]:
time_df.head()

              datetime        date  month  year  season
0  2009-01-01T00:00:00  2009-01-01      1  2009  winter
1  2009-01-01T00:30:00  2009-01-01      1  2009  winter
2  2009-01-01T01:00:00  2009-01-01      1  2009  winter
3  2009-01-01T01:30:00  2009-01-01      1  2009  winter
4  2009-01-01T02:00:00  2009-01-01      1  2009  winter

In [48]:
df = pd.melt(df, id_vars='DATETIME', var_name='name', value_name='mw')
df

                    DATETIME     name      mw
0        2009-01-01T00:00:00      GAS  8367.0
1        2009-01-01T00:30:00      GAS  8495.0
2        2009-01-01T01:00:00      GAS  8471.0
3        2009-01-01T01:30:00      GAS  8318.0
4        2009-01-01T02:00:00      GAS  8295.0
...                      ...      ...     ...
3368404  2026-06-20T11:00:00  STORAGE     0.0
3368405  2026-06-20T11:30:00  STORAGE     0.0
3368406  2026-06-20T12:00:00  STORAGE     0.0
3368407  2026-06-20T12:30:00  STORAGE     0.0
3368408  2026-06-20T13:00:00  STORAGE     0.0

[3368409 rows x 3 columns]

In [64]:
demand_files = glob.glob(r"..\data\raw\demand\demanddata_*.csv")
demand_df = pd.concat([pd.read_csv(f) for f in demand_files], ignore_index=True)
demand_df.head()

,SETTLEMENT_DATE,SETTLEMENT_PERIOD,ND,TSD,ENGLAND_WALES_DEMAND,EMBEDDED_WIND_GENERATION,EMBEDDED_WIND_CAPACITY,EMBEDDED_SOLAR_GENERATION,EMBEDDED_SOLAR_CAPACITY,NON_BM_STOR,...,IFA2_FLOW,BRITNED_FLOW,MOYLE_FLOW,EAST_WEST_FLOW,NEMO_FLOW,NSL_FLOW,ELECLINK_FLOW,VIKING_FLOW,GREENLINK_FLOW,SCOTTISH_TRANSFER
0,01-JAN-2009,1,37910,38704,33939,54,1403,0,0,0,...,0,0,-161,0,0,NaN,NaN,NaN,NaN,NaN
1,01-JAN-2009,2,38047,38964,34072,53,1403,0,0,0,...,0,0,-160,0,0,NaN,NaN,NaN,NaN,NaN
2,01-JAN-2009,3,37380,38651,33615,53,1403,0,0,0,...,0,0,-160,0,0,NaN,NaN,NaN,NaN,NaN
3,01-JAN-2009,4,36426,37775,32526,50,1403,0,0,0,...,0,0,-160,0,0,NaN,NaN,NaN,NaN,NaN
4,01-JAN-2009,5,35687,37298,31877,50,1403,0,0,0,...,0,0,-160,0,0,NaN,NaN,NaN,NaN,NaN

In [ ]:
# COnvert settlement date into ISO format and add setllement periods converted to time
demand_df['datetime'] = (
    pd.to_datetime(demand_df['SETTLEMENT_DATE'])
    + pd.to_timedelta((demand_df['SETTLEMENT_PERIOD'] - 1) * 30, unit='m')
).dt.strftime('%Y-%m-%dT%H:%M:%S')

C:\Users\rufus\AppData\Local\Temp\ipykernel_10592\3650251851.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(demand_df['SETTLEMENT_DATE'])

In [66]:
demand_df.head()

,SETTLEMENT_DATE,SETTLEMENT_PERIOD,ND,TSD,ENGLAND_WALES_DEMAND,EMBEDDED_WIND_GENERATION,EMBEDDED_WIND_CAPACITY,EMBEDDED_SOLAR_GENERATION,EMBEDDED_SOLAR_CAPACITY,NON_BM_STOR,...,BRITNED_FLOW,MOYLE_FLOW,EAST_WEST_FLOW,NEMO_FLOW,NSL_FLOW,ELECLINK_FLOW,VIKING_FLOW,GREENLINK_FLOW,SCOTTISH_TRANSFER,datetime
0,01-JAN-2009,1,37910,38704,33939,54,1403,0,0,0,...,0,-161,0,0,NaN,NaN,NaN,NaN,NaN,2009-01-01T00:00:00
1,01-JAN-2009,2,38047,38964,34072,53,1403,0,0,0,...,0,-160,0,0,NaN,NaN,NaN,NaN,NaN,2009-01-01T00:30:00
2,01-JAN-2009,3,37380,38651,33615,53,1403,0,0,0,...,0,-160,0,0,NaN,NaN,NaN,NaN,NaN,2009-01-01T01:00:00
3,01-JAN-2009,4,36426,37775,32526,50,1403,0,0,0,...,0,-160,0,0,NaN,NaN,NaN,NaN,NaN,2009-01-01T01:30:00
4,01-JAN-2009,5,35687,37298,31877,50,1403,0,0,0,...,0,-160,0,0,NaN,NaN,NaN,NaN,NaN,2009-01-01T02:00:00

In [79]:
import requests, time
import datetime as dt

url = 'https://data.elexon.co.uk/bmrs/api/v1/balancing/pricing/market-index'

start   = dt.datetime(2018, 1, 1) # MID data begins ~here
end     = dt.datetime.now() # up to today
current = start

all_records = [] # the accumulator across all windows

while current < end:
    window_end = current + dt.timedelta(days=7) # this window's far edge
    params = {
        'from': current.strftime('%Y-%m-%dT%H:%MZ'),
        'to':   window_end.strftime('%Y-%m-%dT%H:%MZ'),
    }
    r = requests.get(url, params=params)
    all_records.extend(r.json()['data'])
    print(current)
    current = window_end # advance the window
    time.sleep(0.1)                                   

price_df = pd.DataFrame(all_records)

2018-01-01 00:00:00
2018-01-08 00:00:00
2018-01-15 00:00:00
2018-01-22 00:00:00
2018-01-29 00:00:00
2018-02-05 00:00:00
2018-02-12 00:00:00
2018-02-19 00:00:00
2018-02-26 00:00:00
2018-03-05 00:00:00
2018-03-12 00:00:00
2018-03-19 00:00:00
2018-03-26 00:00:00
2018-04-02 00:00:00
2018-04-09 00:00:00
2018-04-16 00:00:00
2018-04-23 00:00:00
2018-04-30 00:00:00
2018-05-07 00:00:00
2018-05-14 00:00:00
2018-05-21 00:00:00
2018-05-28 00:00:00
2018-06-04 00:00:00
2018-06-11 00:00:00
2018-06-18 00:00:00
2018-06-25 00:00:00
2018-07-02 00:00:00
2018-07-09 00:00:00
2018-07-16 00:00:00
2018-07-23 00:00:00
2018-07-30 00:00:00
2018-08-06 00:00:00
2018-08-13 00:00:00
2018-08-20 00:00:00
2018-08-27 00:00:00
2018-09-03 00:00:00
2018-09-10 00:00:00
2018-09-17 00:00:00
2018-09-24 00:00:00
2018-10-01 00:00:00
2018-10-08 00:00:00
2018-10-15 00:00:00
2018-10-22 00:00:00
2018-10-29 00:00:00
2018-11-05 00:00:00
2018-11-12 00:00:00
2018-11-19 00:00:00
2018-11-26 00:00:00
2018-12-03 00:00:00
2018-12-10 00:00:00
2018-12-17 00:00:00
2018-12-24 00:00:00
2018-12-31 00:00:00
2019-01-07 00:00:00
2019-01-14 00:00:00
2019-01-21 00:00:00
2019-01-28 00:00:00
2019-02-04 00:00:00
2019-02-11 00:00:00
2019-02-18 00:00:00
2019-02-25 00:00:00
2019-03-04 00:00:00
2019-03-11 00:00:00
2019-03-18 00:00:00
2019-03-25 00:00:00
2019-04-01 00:00:00
2019-04-08 00:00:00
2019-04-15 00:00:00
2019-04-22 00:00:00
2019-04-29 00:00:00
2019-05-06 00:00:00
2019-05-13 00:00:00
2019-05-20 00:00:00
2019-05-27 00:00:00
2019-06-03 00:00:00
2019-06-10 00:00:00
2019-06-17 00:00:00
2019-06-24 00:00:00
2019-07-01 00:00:00
2019-07-08 00:00:00
2019-07-15 00:00:00
2019-07-22 00:00:00
2019-07-29 00:00:00
2019-08-05 00:00:00
2019-08-12 00:00:00
2019-08-19 00:00:00
2019-08-26 00:00:00
2019-09-02 00:00:00
2019-09-09 00:00:00
2019-09-16 00:00:00
2019-09-23 00:00:00
2019-09-30 00:00:00
2019-10-07 00:00:00
2019-10-14 00:00:00
2019-10-21 00:00:00
2019-10-28 00:00:00
2019-11-04 00:00:00
2019-11-11 00:00:00
2019-11-18 00:00:00
2019-11-25 00:00:00
2019-12-02 00:00:00
2019-12-09 00:00:00
2019-12-16 00:00:00
2019-12-23 00:00:00
2019-12-30 00:00:00
2020-01-06 00:00:00
2020-01-13 00:00:00
2020-01-20 00:00:00
2020-01-27 00:00:00
2020-02-03 00:00:00
2020-02-10 00:00:00
2020-02-17 00:00:00
2020-02-24 00:00:00
2020-03-02 00:00:00
2020-03-09 00:00:00
2020-03-16 00:00:00
2020-03-23 00:00:00
2020-03-30 00:00:00
2020-04-06 00:00:00
2020-04-13 00:00:00
2020-04-20 00:00:00
2020-04-27 00:00:00
2020-05-04 00:00:00
2020-05-11 00:00:00
2020-05-18 00:00:00
2020-05-25 00:00:00
2020-06-01 00:00:00
2020-06-08 00:00:00
2020-06-15 00:00:00
2020-06-22 00:00:00
2020-06-29 00:00:00
2020-07-06 00:00:00
2020-07-13 00:00:00
2020-07-20 00:00:00
2020-07-27 00:00:00
2020-08-03 00:00:00
2020-08-10 00:00:00
2020-08-17 00:00:00
2020-08-24 00:00:00
2020-08-31 00:00:00
2020-09-07 00:00:00
2020-09-14 00:00:00
2020-09-21 00:00:00
2020-09-28 00:00:00
2020-10-05 00:00:00
2020-10-12 00:00:00
2020-10-19 00:00:00
2020-10-26 00:00:00
2020-11-02 00:00:00
2020-11-09 00:00:00
2020-11-16 00:00:00
2020-11-23 00:00:00
2020-11-30 00:00:00
2020-12-07 00:00:00
2020-12-14 00:00:00
2020-12-21 00:00:00
2020-12-28 00:00:00
2021-01-04 00:00:00
2021-01-11 00:00:00
2021-01-18 00:00:00
2021-01-25 00:00:00
2021-02-01 00:00:00
2021-02-08 00:00:00
2021-02-15 00:00:00
2021-02-22 00:00:00
2021-03-01 00:00:00
2021-03-08 00:00:00
2021-03-15 00:00:00
2021-03-22 00:00:00
2021-03-29 00:00:00
2021-04-05 00:00:00
2021-04-12 00:00:00
2021-04-19 00:00:00
2021-04-26 00:00:00
2021-05-03 00:00:00
2021-05-10 00:00:00
2021-05-17 00:00:00
2021-05-24 00:00:00
2021-05-31 00:00:00
2021-06-07 00:00:00
2021-06-14 00:00:00
2021-06-21 00:00:00
2021-06-28 00:00:00
2021-07-05 00:00:00
2021-07-12 00:00:00
2021-07-19 00:00:00
2021-07-26 00:00:00
2021-08-02 00:00:00
2021-08-09 00:00:00
2021-08-16 00:00:00
2021-08-23 00:00:00
2021-08-30 00:00:00
2021-09-06 00:00:00
2021-09-13 00:00:00
2021-09-20 00:00:00
2021-09-27 00:00:00
2021-10-04 00:00:00
2021-10-11 00:00:00
2021-10-18 00:00:00
2021-10-25 00:00:00
2021-11-01 00:00:00
2021-11-08 00:00:00
2021-11-15 00:00:00
2021-11-22 00:00:00
2021-11-29 00:00:00
2021-12-06 00:00:00
2021-12-13 00:00:00
2021-12-20 00:00:00
2021-12-27 00:00:00
2022-01-03 00:00:00
2022-01-10 00:00:00
2022-01-17 00:00:00
2022-01-24 00:00:00
2022-01-31 00:00:00
2022-02-07 00:00:00
2022-02-14 00:00:00
2022-02-21 00:00:00
2022-02-28 00:00:00
2022-03-07 00:00:00
2022-03-14 00:00:00
2022-03-21 00:00:00
2022-03-28 00:00:00
2022-04-04 00:00:00
2022-04-11 00:00:00
2022-04-18 00:00:00
2022-04-25 00:00:00
2022-05-02 00:00:00
2022-05-09 00:00:00
2022-05-16 00:00:00
2022-05-23 00:00:00
2022-05-30 00:00:00
2022-06-06 00:00:00
2022-06-13 00:00:00
2022-06-20 00:00:00
2022-06-27 00:00:00
2022-07-04 00:00:00
2022-07-11 00:00:00
2022-07-18 00:00:00
2022-07-25 00:00:00
2022-08-01 00:00:00
2022-08-08 00:00:00
2022-08-15 00:00:00
2022-08-22 00:00:00
2022-08-29 00:00:00
2022-09-05 00:00:00
2022-09-12 00:00:00
2022-09-19 00:00:00
2022-09-26 00:00:00
2022-10-03 00:00:00
2022-10-10 00:00:00
2022-10-17 00:00:00
2022-10-24 00:00:00
2022-10-31 00:00:00
2022-11-07 00:00:00
2022-11-14 00:00:00
2022-11-21 00:00:00
2022-11-28 00:00:00
2022-12-05 00:00:00
2022-12-12 00:00:00
2022-12-19 00:00:00
2022-12-26 00:00:00
2023-01-02 00:00:00
2023-01-09 00:00:00
2023-01-16 00:00:00
2023-01-23 00:00:00
2023-01-30 00:00:00
2023-02-06 00:00:00
2023-02-13 00:00:00
2023-02-20 00:00:00
2023-02-27 00:00:00
2023-03-06 00:00:00
2023-03-13 00:00:00
2023-03-20 00:00:00
2023-03-27 00:00:00
2023-04-03 00:00:00
2023-04-10 00:00:00
2023-04-17 00:00:00
2023-04-24 00:00:00
2023-05-01 00:00:00
2023-05-08 00:00:00
2023-05-15 00:00:00
2023-05-22 00:00:00
2023-05-29 00:00:00
2023-06-05 00:00:00
2023-06-12 00:00:00
2023-06-19 00:00:00
2023-06-26 00:00:00
2023-07-03 00:00:00
2023-07-10 00:00:00
2023-07-17 00:00:00
2023-07-24 00:00:00
2023-07-31 00:00:00
2023-08-07 00:00:00
2023-08-14 00:00:00
2023-08-21 00:00:00
2023-08-28 00:00:00
2023-09-04 00:00:00
2023-09-11 00:00:00
2023-09-18 00:00:00
2023-09-25 00:00:00
2023-10-02 00:00:00
2023-10-09 00:00:00
2023-10-16 00:00:00
2023-10-23 00:00:00
2023-10-30 00:00:00
2023-11-06 00:00:00
2023-11-13 00:00:00
2023-11-20 00:00:00
2023-11-27 00:00:00
2023-12-04 00:00:00
2023-12-11 00:00:00
2023-12-18 00:00:00
2023-12-25 00:00:00
2024-01-01 00:00:00
2024-01-08 00:00:00
2024-01-15 00:00:00
2024-01-22 00:00:00
2024-01-29 00:00:00
2024-02-05 00:00:00
2024-02-12 00:00:00
2024-02-19 00:00:00
2024-02-26 00:00:00
2024-03-04 00:00:00
2024-03-11 00:00:00
2024-03-18 00:00:00
2024-03-25 00:00:00
2024-04-01 00:00:00
2024-04-08 00:00:00
2024-04-15 00:00:00
2024-04-22 00:00:00
2024-04-29 00:00:00
2024-05-06 00:00:00
2024-05-13 00:00:00
2024-05-20 00:00:00
2024-05-27 00:00:00
2024-06-03 00:00:00
2024-06-10 00:00:00
2024-06-17 00:00:00
2024-06-24 00:00:00
2024-07-01 00:00:00
2024-07-08 00:00:00
2024-07-15 00:00:00
2024-07-22 00:00:00
2024-07-29 00:00:00
2024-08-05 00:00:00
2024-08-12 00:00:00
2024-08-19 00:00:00
2024-08-26 00:00:00
2024-09-02 00:00:00
2024-09-09 00:00:00
2024-09-16 00:00:00
2024-09-23 00:00:00
2024-09-30 00:00:00
2024-10-07 00:00:00
2024-10-14 00:00:00
2024-10-21 00:00:00
2024-10-28 00:00:00
2024-11-04 00:00:00
2024-11-11 00:00:00
2024-11-18 00:00:00
2024-11-25 00:00:00
2024-12-02 00:00:00
2024-12-09 00:00:00
2024-12-16 00:00:00
2024-12-23 00:00:00
2024-12-30 00:00:00
2025-01-06 00:00:00
2025-01-13 00:00:00
2025-01-20 00:00:00
2025-01-27 00:00:00
2025-02-03 00:00:00
2025-02-10 00:00:00
2025-02-17 00:00:00
2025-02-24 00:00:00
2025-03-03 00:00:00
2025-03-10 00:00:00
2025-03-17 00:00:00
2025-03-24 00:00:00
2025-03-31 00:00:00
2025-04-07 00:00:00
2025-04-14 00:00:00
2025-04-21 00:00:00
2025-04-28 00:00:00
2025-05-05 00:00:00
2025-05-12 00:00:00
2025-05-19 00:00:00
2025-05-26 00:00:00
2025-06-02 00:00:00
2025-06-09 00:00:00
2025-06-16 00:00:00
2025-06-23 00:00:00
2025-06-30 00:00:00
2025-07-07 00:00:00
2025-07-14 00:00:00
2025-07-21 00:00:00
2025-07-28 00:00:00
2025-08-04 00:00:00
2025-08-11 00:00:00
2025-08-18 00:00:00
2025-08-25 00:00:00
2025-09-01 00:00:00
2025-09-08 00:00:00
2025-09-15 00:00:00
2025-09-22 00:00:00
2025-09-29 00:00:00
2025-10-06 00:00:00
2025-10-13 00:00:00
2025-10-20 00:00:00
2025-10-27 00:00:00
2025-11-03 00:00:00
2025-11-10 00:00:00
2025-11-17 00:00:00
2025-11-24 00:00:00
2025-12-01 00:00:00
2025-12-08 00:00:00
2025-12-15 00:00:00
2025-12-22 00:00:00
2025-12-29 00:00:00
2026-01-05 00:00:00
2026-01-12 00:00:00
2026-01-19 00:00:00
2026-01-26 00:00:00
2026-02-02 00:00:00
2026-02-09 00:00:00
2026-02-16 00:00:00
2026-02-23 00:00:00
2026-03-02 00:00:00
2026-03-09 00:00:00
2026-03-16 00:00:00
2026-03-23 00:00:00
2026-03-30 00:00:00
2026-04-06 00:00:00
2026-04-13 00:00:00
2026-04-20 00:00:00
2026-04-27 00:00:00
2026-05-04 00:00:00
2026-05-11 00:00:00
2026-05-18 00:00:00
2026-05-25 00:00:00
2026-06-01 00:00:00
2026-06-08 00:00:00
2026-06-15 00:00:00
2026-06-22 00:00:00

In [98]:
price_df['pv'] = price_df['price'] * price_df['volume']
grouped_price_df = price_df.groupby('startTime', as_index=False)[['pv', 'volume']].sum()
grouped_price_df['price'] = grouped_price_df['pv'] / grouped_price_df['volume']
grouped_price_df = grouped_price_df.dropna(subset=['price'])
grouped_price_df['startTime'] = pd.to_datetime(grouped_price_df['startTime']).dt.strftime('%Y-%m-%dT%H:%M:%S')

grouped_price_df

                  startTime           pv   volume  price
0       2018-01-01T00:00:00   36934.4145   781.35  47.27
1       2018-01-01T00:30:00   31832.7780   655.40  48.57
2       2018-01-01T01:00:00   42980.8800   821.50  52.32
3       2018-01-01T01:30:00   41721.9360   815.20  51.18
4       2018-01-01T02:00:00   32673.0240   709.05  46.08
...                     ...          ...      ...    ...
146688  2026-06-22T12:00:00  274238.0420  3595.15  76.28
146689  2026-06-22T12:30:00  274247.4020  3766.10  72.82
146690  2026-06-22T13:00:00  276008.0400  3982.80  69.30
146691  2026-06-22T13:30:00  291680.9000  4318.00  67.55
146692  2026-06-22T14:00:00  440303.2445  4740.05  92.89

[146091 rows x 4 columns]