## Notebook for intial data exploration

In [2]:
import pandas as pd

In [5]:
df = pd.read_csv(r"..\data\raw\df_fuel_ckan.csv")

In [11]:
df.head()

,DATETIME,GAS,COAL,NUCLEAR,WIND,WIND_EMB,HYDRO,IMPORTS,BIOMASS,OTHER,...,IMPORTS_perc,BIOMASS_perc,OTHER_perc,SOLAR_perc,STORAGE_perc,GENERATION_perc,LOW_CARBON_perc,ZERO_CARBON_perc,RENEWABLE_perc,FOSSIL_perc
0,2009-01-01T00:00:00,8367.0,15037.0,7099.0,248.0,62.0,246.0,2518.0,0.0,0.0,...,7.5,0.0,0.0,0.0,0.0,100.0,22.8,24.5,1.7,69.7
1,2009-01-01T00:30:00,8495.0,15095.0,7088.0,229.0,57.0,245.0,2495.0,0.0,0.0,...,7.4,0.0,0.0,0.0,0.0,100.0,22.6,24.3,1.6,70.0
2,2009-01-01T01:00:00,8471.0,15088.0,7074.0,207.0,52.0,246.0,2465.0,0.0,0.0,...,7.3,0.0,0.0,0.0,0.0,100.0,22.6,24.2,1.5,70.1
3,2009-01-01T01:30:00,8318.0,15035.0,7064.0,191.0,48.0,246.0,2439.0,0.0,0.0,...,7.3,0.0,0.0,0.0,0.0,100.0,22.6,24.3,1.5,70.0
4,2009-01-01T02:00:00,8295.0,15005.0,7052.0,175.0,44.0,246.0,2363.0,0.0,0.0,...,7.1,0.0,0.0,0.0,0.0,100.0,22.7,24.3,1.4,70.2

In [15]:
df.tail()

,DATETIME,GAS,COAL,NUCLEAR,WIND,WIND_EMB,HYDRO,IMPORTS,BIOMASS,OTHER,...,IMPORTS_perc,BIOMASS_perc,OTHER_perc,SOLAR_perc,STORAGE_perc,GENERATION_perc,LOW_CARBON_perc,ZERO_CARBON_perc,RENEWABLE_perc,FOSSIL_perc
306214,2026-06-20T11:00:00,5016.0,0.0,2946.0,4062.0,880.0,195.0,8378.0,1121.0,650.0,...,25.3,3.4,2.0,29.8,0.0,100.0,57.6,59.5,45.3,15.1
306215,2026-06-20T11:30:00,4788.0,0.0,2946.0,4285.0,894.0,181.0,8380.0,1177.0,553.0,...,25.1,3.5,1.7,30.6,0.0,100.0,59.0,61.7,46.7,14.3
306216,2026-06-20T12:00:00,4659.0,0.0,2948.0,4291.0,868.0,179.0,8356.0,1251.0,570.0,...,24.9,3.7,1.7,31.1,0.0,100.0,59.5,62.4,47.0,13.9
306217,2026-06-20T12:30:00,5004.0,0.0,2943.0,4124.0,876.0,180.0,8356.0,1286.0,512.0,...,25.0,3.8,1.5,30.4,0.0,100.0,58.5,60.7,45.9,15.0
306218,2026-06-20T13:00:00,4982.0,0.0,2943.0,4119.0,882.0,180.0,8332.0,1306.0,511.0,...,25.0,3.9,1.5,30.3,0.0,100.0,58.6,60.9,45.8,14.9

In [8]:
df.shape

(306219, 34)

In [21]:
df.columns

Index(['DATETIME', 'GAS', 'COAL', 'NUCLEAR', 'WIND', 'WIND_EMB', 'HYDRO',
       'IMPORTS', 'BIOMASS', 'OTHER', 'SOLAR', 'STORAGE', 'GENERATION',
       'CARBON_INTENSITY', 'LOW_CARBON', 'ZERO_CARBON', 'RENEWABLE', 'FOSSIL',
       'GAS_perc', 'COAL_perc', 'NUCLEAR_perc', 'WIND_perc', 'WIND_EMB_perc',
       'HYDRO_perc', 'IMPORTS_perc', 'BIOMASS_perc', 'OTHER_perc',
       'SOLAR_perc', 'STORAGE_perc', 'GENERATION_perc', 'LOW_CARBON_perc',
       'ZERO_CARBON_perc', 'RENEWABLE_perc', 'FOSSIL_perc'],
      dtype='object')

In [19]:
df.isnull().sum()

DATETIME            0
GAS                 0
COAL                0
NUCLEAR             0
WIND                0
WIND_EMB            0
HYDRO               0
IMPORTS             0
BIOMASS             0
OTHER               0
SOLAR               0
STORAGE             0
GENERATION          0
CARBON_INTENSITY    0
LOW_CARBON          0
ZERO_CARBON         0
RENEWABLE           0
FOSSIL              0
GAS_perc            0
COAL_perc           0
NUCLEAR_perc        0
WIND_perc           0
WIND_EMB_perc       0
HYDRO_perc          0
IMPORTS_perc        0
BIOMASS_perc        0
OTHER_perc          0
SOLAR_perc          0
STORAGE_perc        0
GENERATION_perc     0
LOW_CARBON_perc     0
ZERO_CARBON_perc    0
RENEWABLE_perc      0
FOSSIL_perc         0
dtype: int64